### ISSUE TITLE
Login jupyterlab

### ISSUE THREAD

**Issue by xielinjiang** [dclong/docker-jupyterlab#15]
```
docker run -d \
    --hostname jupyterlab \
    --log-opt max-size=50m \
    -p 8888:8888 \
    -e DOCKER_USER=$(id -un) \
    -e DOCKER_USER_ID=$(id -u) \
    -e DOCKER_PASSWORD=$(id -un) \
    -e DOCKER_GROUP_ID=$(id -g) \
    -v "$(pwd)":/workdir \
    -v "$(dirname $HOME)":/home_host \
    dclong/jupyterlab /scripts/sys/init.sh
```
I have executed this command, how do I login with my browser to JupyterLab。

**Comment by dclong** [comment]
Please refer to the Section "Get the Token for Login" in the readme. 

BTW, it is suggested that you use https://hub.docker.com/r/dclong/jupyterhub-ds/. If don't like the data science bundle in the Docker image, then try https://github.com/dclong/docker-jupyterhub. It is easier to login a JupyterHub server.
