### ISSUE TITLE
Setting password on run command

### ISSUE THREAD

**Issue by eliorc** [dclong/docker-jupyterlab#6]
Is it possible to set up the password when starting the container?

If not, how can I tell which is the password? Neither the result of `id -u` or `id -un` does not work as the password. (when connecting to localhost:8888 after the container is up)

**Comment by danelowe** [comment]
The examples given in the readme use the detach flag (`-d`). Either remove that flag to run in foreground with logs, or  run `docker logs <container_id>`

**Comment by dclong** [comment]
@eliorc The option `-e DOCKER_PASSWORD=`id -un` is for setting the password of the user in the Docker not the password of the JupyterLab server. I didn't set a password but instead a live token is used. There are a bunch of ways to get the token:

1. As @danelowe mentioned. 

2. Run the following command to show running servers and their tokens. 
```
docker exec container_name_or_id jupyter notebook list
```


`    docker exec -u $user $1 jupyter notebook list

**Comment by dclong** [comment]
@eliorc 
BTW, if you do prefer password than token, there's another image which you might be interested in: dclong/jupyterhub-ds. It's a docker image for data scientist and have lots of useful packages preinstalled. It's for multiple users and can be login in using user password in the Docker directly.
