### ISSUE TITLE
run-time errors running jupyterlab with docker run

### ISSUE THREAD

**Issue by krokha72** [dclong/docker-jupyterlab#7]
Hi Ben,
Could you help to address run-time error
I am following usage sample you provided with
_docker run -d --log-opt max-size=50m -p 8888:8888 -e DOCKER_USER="id -un" -e DOCKER_USER_ID="id -u" -e DOCKER_PASSWORD="id -un" -v $HOME:/jupyter dclong/jupyterlab__
and getting  following error
_docker: Error response from daemon: create $HOME: "$HOME" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path._
I tried to pass absolute path (c:/tmp/jupyter) but it did not work either
I am using Windows10 and _Docker version 17.09.0-ce, build afdb6d4_
Could you suggest work around please
Thank you
Alex

**Comment by dclong** [comment]
@krokha72 
Unfortunately the usage is for Linux environment only. I don't use Docker on Windows. I personally came across issues with Docker in Win10, e.g., mounting drives, but I couldn't fix it as I've no access to firewall settings (it's a win10 machine in work). If you do want to use the Docker image on Windows, please replace the Linux commands with the the corresponding DOS commands or there output directly. For example `id -un` get the current user name in Linux, so you can use your win user name directly. 

BTW, if you are a data scientist, there are 2 more images you might be interested in: dclong/jupyterlab-ds and dclong/jupyterhub-ds. The come with lots of useful packages preinstalled. dclong/jupyterhub-ds is for multiple users.

**Comment by krokha72** [comment]
Ben, I got it. Thanks for clarifying - I will close the issue
Im new to the docker(.  How do you add more python packages to the image?

**Comment by dclong** [comment]
There's an image named dclong/jupyterlab-py which adds popular Python packages on top of dclong/jupyterlab. You can check the corresponding Dockerfile.

Another way is to open a terminal in JupyterLab and install Python packages you want. This won't persistent the new installed package of course. So it's only suitable for packages that you don't use often.

**Comment by krokha72** [comment]
Thanks a lot for your comments
